### ISSUE TITLE
Main.py Errors 

### ISSUE THREAD

**Issue by ElijahKlein** [ElijahKlein/ECE-461-Project#93]
Integrating main.py errors from Jack's code

**Comment by ElijahKlein** [comment]
Handled both the issues described below:

This issue also sometimes occurs when “./run URL_File.txt” is excuted:

Traceback (most recent call last):

  File "/home/min/a/dananday/Work/ECE461_TA/Auto-grader/repos/ECE-461-Project/main.py", line 62, in <module>

    pullFrequency = creationDate / pullTotal

ZeroDivisionError: division by zero

 

And sometimes this:

Traceback (most recent call last):

  File "/home/min/a/dananday/Work/ECE461_TA/Auto-grader/repos/ECE-461-Project/main.py", line 48, in <module>

    for contributor in allCommits:

TypeError: 'NoneType' object is not iterable
