### ISSUE TITLE
Fixing sub process run issue

### ISSUE THREAD

**Issue by ElijahKlein** [ElijahKlein/ECE-461-Project#96]
Traceback (most recent call last):

  File "/home/min/a/dananday/Work/ECE461_TA/Auto-grader/repos/ECE-461-Project/main.py", line 71, in <module>

    dataString = subprocess.run(executable + args, cwd=None, shell=False, stdout=subprocess.PIPE)

  File "/usr/lib/python3.10/subprocess.py", line 501, in run

    with Popen(*popenargs, **kwargs) as process:

  File "/usr/lib/python3.10/subprocess.py", line 969, in __init__

    self._execute_child(args, executable, preexec_fn, close_fds,

  File "/usr/lib/python3.10/subprocess.py", line 1845, in _execute_child

    raise child_exception_type(errno_num, err_msg, err_filename)

FileNotFoundError: [Errno 2] No such file or directory: '/home/min/a/dananday/Work/ECE461_TA/Auto-grader/repos/ECE-461-Project/NetScoreCalculation/net_score.exe 0 23 1935 141 3185 103.86842105263158 38 7 89'

**Comment by ElijahKlein** [comment]
Found the issue, needed to be in list form not as a full string
